/*
 PureMVC TypeScript by Frederic Saunier <frederic.saunier@puremvc.org>
 PureMVC - Copyright(c) 2006-2012 Futurescale, Inc., Some rights reserved.
 Your reuse is governed by the Creative Commons Attribution 3.0 License
*/

///<reference path='../../../../org/puremvc/typescript/patterns/observer/Observer.ts'/>

module puremvc
{
	"use strict";

	/**
	 * Test the PureMVC Notification class.
	 *
	 * @see puremvc.Notification
	 */
	export class NotificationTest
	{
		/**
		 * The name of the test case - if not provided, one is automatically
		 * generated by the YUITest framework.
		 */
		name:string = "PureMVC Notification class tests",

		/**
		 * Sets up data that is needed by each test.
		 */
		setUp()
		{
		}

		/**
		 * Cleans up everything that was created by setUp().
		 */
		tearDown()
		{
		}

		/**
		 * Tests setting and getting the name using Notification class accessor
		 * methods.
		 */
		testNameAccessors()
		{
			var Notification = extract("puremvc.Notification");

			// Create a new Notification and use accessors to set the note name
			var note/*Notification*/ = new Notification('TestNote');

			// test assertions
			YUITest.Assert.areEqual
			(
				'TestNote',
				note.getName(),
				"Expecting note.getName() == 'TestNote'"
			);
		}

		/**
		 * Tests setting and getting the body using Notification class accessor
		 * methods.
		 */
		testBodyAccessors()
		{
			var Notification = extract("puremvc.Notification");

			// Create a new Notification and use accessors to set the body
			var note/*Notification*/ = new Notification(null);
			note.setBody(5);

			// test assertions
			YUITest.Assert.areSame
			(
				5,
				note.getBody(),
				"Expecting note.getBody() === 5"
			);
		}

		/**
		 * Tests setting the name and body using the Notification class
		 * Constructor.
		 */
		testConstructor()
		{
			var Notification = extract("puremvc.Notification");

			// Create a new Notification using the Constructor to set the note name and body
			var note/*Notification*/ = new Notification( 'TestNote', 5, 'TestNoteType' );

			// test assertions
			YUITest.Assert.areEqual
			(
				"TestNote",
				note.getName(),
				"Expecting note.getName() == 'TestNote'"
			);

			YUITest.Assert.areSame
			(
				5,
				note.getBody(),
				"Expecting note.getBody() === 5"
			);

			YUITest.Assert.areEqual
			(
				"TestNoteType",
				note.getType(),
				"Expecting note.getType() == 'TestNoteType'"
			);
		}

		/**
		 * Tests the toString method of the notification
		 */
		testToString()
		{
			var Notification = extract("puremvc.Notification");

			// Create a new Notification and use accessors to set the note name
			var note/*Notification*/ = new Notification( 'TestNote', [1,3,5], 'TestType' );
			var ts/*String*/ = "Notification Name: TestNote\nBody:1,3,5\nType:TestType";

			// test assertions
			YUITest.Assert.areEqual
			(
				ts,
				note.toString(),
				"Expecting note.testToString() == '" + ts + "'"
			);
		}
	}
}

var notificationTest = new NotificationTest();
var NotificationTestCase = new YUITest.TestCase(notificationTest);